services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=db;Database=WorkoutTracker;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true;
      FatSecret__ClientId: ${FATSECRET_CLIENT_ID}
      FatSecret__ClientSecret: ${FATSECRET_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  sqlserverdata:
